#!/usr/bin/python
# coding: utf-8

""" Common functions to write pipelines """

def remove_files(_, files):
    """
    Fully remove files generated by a Node, once they aren't needed anymore.
    This function is meant to be used in a Nipype Function Node.

    Parameters:
    - _: input only used for triggering the Node
    - files: str or list, a single filename or a list of absolute filenames to remove
    """
    # This import must stay inside the function, as required by Nipype
    from os import remove

    if isinstance(files, str):
        files = [files]

    try:
        for file in files:
            remove(file)
    except OSError as error:
        print(error)
    else:
        print('The following files were successfully deleted.')
        print(files)
