[general]
title = "Configuration for the NARPS open pipelines project, to be used inside the nipype/nipype:py38 docker container"
config_type = "custom"

[directories]
dataset = "/work/data/original/ds001734/"
reproduced_results = "/work/run/reproduced/"
narps_results = "/work/data/results/"

[runner]
nb_procs = 8 # Maximum number of threads executed by the runner
nb_trials = 3 # Maximum number of executions to have the pipeline executed completely

[pipelines]
remove_unused_data = true # set to true to activate remove nodes of pipelines

[results]
neurovault_naming = true # true if results files are saved using the neurovault naming, false if they use naming of narps
